// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TdBlanc.Models.EntityFramework;

#nullable disable

namespace TdBlanc.Migrations
{
    [DbContext(typeof(CommandeBDContext))]
    [Migration("20251022162221_modifmodels")]
    partial class modifmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TdBlanc.Models.Animal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ANI_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnimal"));

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("ANI_NOM");

                    b.Property<double>("Poid")
                        .HasColumnType("double precision")
                        .HasColumnName("ANI_POID");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("ANI_REFERENCE");

                    b.HasKey("IdAnimal");

                    b.ToTable("T_E_ANIMAL_ANI", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
