// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TdBlanc.Models.EntityFramework;

#nullable disable

namespace TdBlanc.Migrations
{
    [DbContext(typeof(CommandeBDContext))]
    [Migration("20251010134535_modifschema11")]
    partial class modifschema11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TdBlanc.Models.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("COM_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCommande"));

                    b.Property<double>("Montant")
                        .HasColumnType("double precision")
                        .HasColumnName("COM_MONTANT");

                    b.Property<string>("NomArticle")
                        .HasColumnType("text")
                        .HasColumnName("COM_NOMARTICLE");

                    b.Property<int?>("UTI_ID")
                        .HasColumnType("integer");

                    b.HasKey("IdCommande");

                    b.HasIndex("UTI_ID");

                    b.ToTable("T_E_COMMANDE_COM", "public");
                });

            modelBuilder.Entity("TdBlanc.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UTI_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<int>("CodePostal")
                        .HasMaxLength(5)
                        .HasColumnType("integer")
                        .HasColumnName("UTI_CODEPOSTAL");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("UTI_NOM");

                    b.Property<string>("NumeroRue")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("UTI_NUMERORUE");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("UTI_PRENOM");

                    b.Property<string>("Rue")
                        .HasColumnType("text")
                        .HasColumnName("UTI_RUE");

                    b.Property<string>("Ville")
                        .HasColumnType("text")
                        .HasColumnName("UTI_VILLE");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("T_E_UTILISATEUR_UTI", "public");
                });

            modelBuilder.Entity("TdBlanc.Models.Commande", b =>
                {
                    b.HasOne("TdBlanc.Models.Utilisateur", "CommandeUtlisateurNavigation")
                        .WithMany("Commandes")
                        .HasForeignKey("UTI_ID")
                        .HasConstraintName("FK_T_E_COMMANDE_COM_T_E_UTILISATEUR_UTI");

                    b.Navigation("CommandeUtlisateurNavigation");
                });

            modelBuilder.Entity("TdBlanc.Models.Utilisateur", b =>
                {
                    b.Navigation("Commandes");
                });
#pragma warning restore 612, 618
        }
    }
}
